title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://astrovar.github.io/test-pages-deployment/docs

aux_links:
  Template Repository: https://github.com/astrovar/test-pages-deployment/docs
